-- Cero Grados v80
create table if not exists public.cero_grados_orders (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 customer text not null,
 notes text,
 type text,
 product_type text,
 scoops int not null default 0,
 flavor jsonb not null default '{}'::jsonb,
 base numeric not null default 0,
 included jsonb not null default '[]'::jsonb,
 extras jsonb not null default '[]'::jsonb,
 mochis jsonb not null default '[]'::jsonb,
 total numeric not null default 0,
 status text not null default 'pendiente_pago',
 history jsonb not null default '[]'::jsonb,
 paid_at timestamptz
);

alter table public.cero_grados_orders enable row level security;

drop policy if exists "v80_read" on public.cero_grados_orders;
drop policy if exists "v80_insert" on public.cero_grados_orders;
drop policy if exists "v80_update" on public.cero_grados_orders;

create policy "v80_read" on public.cero_grados_orders
for select to anon using (true);

create policy "v80_insert" on public.cero_grados_orders
for insert to anon with check (true);

create policy "v80_update" on public.cero_grados_orders
for update to anon using (true) with check (true);

grant usage on schema public to anon;
grant select, insert, update on public.cero_grados_orders to anon;
grant usage, select on sequence public.cero_grados_orders_id_seq to anon;

notify pgrst, 'reload schema';
