create table if not exists public.cero_grados_orders (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 customer text not null,
 notes text,
 type text,
 product_type text,
 scoops int not null default 0,
 flavor jsonb not null default '{}'::jsonb,
 base numeric not null default 0,
 included jsonb not null default '[]'::jsonb,
 extras jsonb not null default '[]'::jsonb,
 mochis jsonb not null default '[]'::jsonb,
 total numeric not null default 0,
 status text not null default 'pendiente_pago',
 history jsonb not null default '[]'::jsonb,
 paid_at timestamptz
);

alter table public.cero_grados_orders add column if not exists type text;
alter table public.cero_grados_orders add column if not exists product_type text;
alter table public.cero_grados_orders add column if not exists mochis jsonb not null default '[]'::jsonb;
alter table public.cero_grados_orders add column if not exists paid_at timestamptz;

alter table public.cero_grados_orders enable row level security;

drop policy if exists "cg_select" on public.cero_grados_orders;
drop policy if exists "cg_insert" on public.cero_grados_orders;
drop policy if exists "cg_update" on public.cero_grados_orders;

create policy "cg_select" on public.cero_grados_orders for select to anon using (true);
create policy "cg_insert" on public.cero_grados_orders for insert to anon with check (true);
create policy "cg_update" on public.cero_grados_orders for update to anon using (true) with check (true);
